sudo: true
language: java
script:
  - clojure -Aclj-test
  - clojure -Acljs-test
  - clojure -Acljs-test -x planck
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.447.sh
  - chmod +x linux-install-1.10.1.447.sh
  - sudo ./linux-install-1.10.1.447.sh
  - sudo add-apt-repository -y ppa:mfikes/planck
  - sudo apt-get update -y
  - sudo apt-get install -y planck
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - $HOME/.gitlibs
    - node_modules
    - .cpcache
    - cljs-test-runner-out
